webshop-client/config/routes.rb
Rails.application.routes.draw do
  root to: 'application#home', as: 'home'

  # User paths
  get 'register' => 'users#new'
  post 'create' => 'users#create', as: 'create_user'
  get 'upload_page' => 'users#upload_page', as: 'upload_page'
  post 'upload' => 'users#upload', as: 'upload'
  get 'admin_page' => 'users#admin_page', as: 'admin_page'
  delete 'delete' => 'users#destroy', as: 'delete_user'
  get 'edit_user' => 'users#edit_user', as: 'edit_user'
  post 'update_user' => 'users#update', as: 'update_user'


  # Caff paths
  get 'search' => 'caff#search', as: 'search'
  get 'download' => 'caff#download', as: 'download_caff'
  get 'show' => 'caff#show', as: 'show_caff'
  post 'post_comment' => 'caff#post_comment', as: 'post_comment'

  # Session paths
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'pages/home'
  get 'pages/log_in'
  get 'pages/register'
  get 'pages/show'
  get 'pages/upload'
  get 'pages/my_profile'
  get 'pages/admin_page'
  get 'pages/edit_profile'
end

webshop-client/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :verify_user_logged_in, except: [:new, :create]
  before_action :verify_is_admin, only: [:admin_page, :destroy, :edit_user, :update]

  def new
  end

  def create
    req = SwaggerClient::RegistrationRequest.new user_params
    data = @@api_auth.register req
    if data.status == "SUCCESS"
      flash[:success] = "Successful registration!"
      redirect_to home_path
    else
      flash[:error] = "Something went wrong... Possible reasons: Username already in use / Passwords did not match"
      redirect_back fallback_location: home_path
    end
  end

  def upload_page
    @is_admin = session[:username] == "root"
  end

  def upload
    uploaded_file = params[:picture]
    filename = uploaded_file.original_filename
    file = uploaded_file.tempfile.open.read.force_encoding(Encoding::UTF_8)
    file_b64 = Base64.encode64(file)
    name = filename.partition(".").first
    extension = filename.partition(".").last.upcase

    req = SwaggerClient::UploadRequest.new Hash[:uploader_uuid => session[:user_uuid], :required_file_name => name,
                                                :file_content_as_string => file_b64, :file_type => extension]
    token = session[:token]
    data, header = @@api_user.upload req, {:header_params => {"Authorization" => token}}
    session[:token] = header[:Authorization]
    flash[:notice] = "File upload finished."
    redirect_to home_path
  end

  def admin_page
    @users = []
    token = session[:token]
    data, header = @@api_admin.list_users :header_params => {"Authorization" => token}
    session[:token] = header[:Authorization]
    if !data.nil?
      filtered_users = data.users.select {|hash| hash[:username] != "root"}
      @users = filtered_users
    end
  end

  def destroy
    user_uuid = params[:uuid]
    token = session[:token]
    data, header = @@api_admin.remove_user user_uuid, {:header_params => {"Authorization" => token}}
    session[:token] = header[:Authorization]
    redirect_back fallback_location: home_path
  end

  def edit_user
    user_hash = params[:selected_user].permit(:uuid, :username, :email, :dateOfBirth, :registrationDate).to_h
    @user = SwaggerClient::UserResult.build_from_hash user_hash
  end

  def update
    token = session[:token]
    req = SwaggerClient::UpdateUserRequest.new update_params
    data, header = @@api_admin.update_user req, params[:user][:uuid], {:header_params => {"Authorization" => token}}
    session[:token] = header[:Authorization]
    redirect_to admin_page_path
  end

  private
  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirm, :date_of_birth).to_h
  end

  def verify_user_logged_in
    if session[:user_uuid].nil?
      flash[:error] = "Only logged in users can access this page!"
      redirect_back fallback_location: home_path
    end
  end

  def verify_is_admin
    @is_admin = session[:username] == "root"
    unless @is_admin
      flash[:error] = "Unauthorized access!"
      redirect_back fallback_location: home_path
    end
  end

  def update_params
    params.require(:user).permit(:email, :date_of_birth).to_h
  end


end

webshop-client/app/views/users/_form.html.erb
<%= form_for :user, url: create_user_path, method: :post do |form| %>

  <div class="field">
    <%= form.label :username, class: "label" %>
    <%= form.text_field :username, class: "input", required: true, :maxlength => 50, id: "userName" %>
  </div>

  <div class="field">
    <%= form.label :email, class: "label"  %>
    <%= form.email_field :email, class: "input", required: true, :maxlength => 50 %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth, class: "label"  %>
    <%= form.date_field :date_of_birth, class: "input", required: true, max: Date.today %>
  </div>

  <div class="field">
    <%= form.label :password, class: "label"  %>
    <%= form.password_field :password, class: "input", required: true, id: "password" %>
  </div>

  <div class="field">
    <%= form.label :password, class: "label"  %>
    <%= form.password_field :password_confirm, class: "input", required: true, id: "passwordValidation"%>
    <span id='message'></span>
  </div>

  <div class="actions">
    <%= form.submit :Submit, class: "button is-link disabled", id: "submitBtn"%>
  </div>
<% end %>

webshop-client/app/views/users/admin_page.html.erb
<div class="tile is-ancestor">
  <div class="tile is-parent">
    <div class="tile is-child is-2">
      <%= render partial: 'shared/menu', :locals => {:selected_menu_item => "Admin Page", :admin_user => @is_admin} %>
    </div>

    <div class="tile is-child is-8">
      <div class="section">
        <div class="content">
          <h1 class="title">
            Admin page
          </h1>

          <table class="table">
            <thead>
            <tr>
              <th>Username</th>
              <th>Email</th>
              <th>Date of birth</th>
              <th>Action</th>
            </tr>
            </thead>

            <tbody>
            <% @users.each do |user_hash| %>
              <% user = SwaggerClient::UserResult.build_from_hash user_hash %>
              <tr>
                <th><%= user.username %></th>
                <th><%= user.email %></th>
                <th><%= user.date_of_birth %></th>
                <th><%= link_to "Edit", edit_user_path(:selected_user => user_hash) %>/<%= link_to "Delete", delete_user_path(:uuid => user.uuid), data: {:confirm => 'Are you sure?'}, :method => :delete%></th>
              </tr>
            <% end %>
            </tbody>
          </table>

        </div>
      </div>
    </div>

    <div class="tile is-child is-2"></div>
  </div>
</div>

webshop-client/app/views/users/edit_user.html.erb
<div class="tile is-ancestor">
  <div class="tile is-parent">
    <div class="tile is-child is-2">
      <%= render partial: 'shared/menu', :locals => {:selected_menu_item => "Admin Page", :admin_user => @is_admin} %>
    </div>

    <div class="tile is-child is-8">
      <div class="section">
        <div class="content">
          <h1 class="title">
            Edit profile of <%= @user.username %>
          </h1>

          <%= form_for :user, url: update_user_path, method: :post do |form| %>
            <%= form.hidden_field :uuid %>
            <div class="field">
              <%= form.label :email, class: "label"  %>
              <%= form.email_field :email, class: "input", required: true %>
            </div>

            <div class="field">
              <%= form.label :date_of_birth, class: "label"  %>
              <%= form.date_field :date_of_birth, class: "input", required: true, max: Date.today %>
            </div>

            <div class="actions">
              <%= form.submit :Save, class: "button is-link disabled", id: "submitBtn"%>
            </div>
          <% end %>

        </div>
      </div>
    </div>

    <div class="tile is-child is-2"></div>
  </div>
</div>

webshop-client/app/views/users/new.html.erb
<div class="tile is-ancestor">
  <div class="tile is-parent">
    <div class="tile is-child is-4"></div>

    <div class="tile is-child is-4">
      <div class="section">
        <article class="tile is-child notification is-primary">
          <h1 class="title">Register</h1>
          <%= render 'form', user: @user%>
        </article>
      </div>
    </div>

    <div class="tile is-child is-4"></div>
  </div>
</div>

webshop-client/app/views/users/upload_page.html.erb
<div class="tile is-ancestor">
  <div class="tile is-parent">
    <div class="tile is-child is-2">
      <%= render partial: 'shared/menu', :locals => {:selected_menu_item => "Upload", :admin_user => @is_admin} %>
    </div>

  <div class="tile is-child is-8">
    <div class="section">
      <div class="content">
        <h1 class="title">
          Upload a new CAFF file
        </h1>

        <%= form_tag('upload', multipart: true) do %>
          <div class="field">
            <%= file_field_tag 'picture', required: true%>
          </div>

          <div class="actions">
            <%= submit_tag :Confirm, class: "button is-primary", id: "submitBtn"%>
          </div>
        <% end %>
      </div>


    </div>
  </div>
  <div class="tile is-child is-2"></div>
</div>
</div>