webshop-client/config/routes.rb
Rails.application.routes.draw do
  root to: 'application#home', as: 'home'

  # User paths
  get 'register' => 'users#new'
  post 'create' => 'users#create', as: 'create_user'
  get 'upload_page' => 'users#upload_page', as: 'upload_page'
  post 'upload' => 'users#upload', as: 'upload'
  get 'admin_page' => 'users#admin_page', as: 'admin_page'
  delete 'delete' => 'users#destroy', as: 'delete_user'
  get 'edit_user' => 'users#edit_user', as: 'edit_user'
  post 'update_user' => 'users#update', as: 'update_user'


  # Caff paths
  get 'search' => 'caff#search', as: 'search'
  get 'download' => 'caff#download', as: 'download_caff'
  get 'show' => 'caff#show', as: 'show_caff'
  post 'post_comment' => 'caff#post_comment', as: 'post_comment'

  # Session paths
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'pages/home'
  get 'pages/log_in'
  get 'pages/register'
  get 'pages/show'
  get 'pages/upload'
  get 'pages/my_profile'
  get 'pages/admin_page'
  get 'pages/edit_profile'
end

webshop-client/app/controllers/caff_controller.rb
class CaffController < ApplicationController
  before_action :verify_user_logged_in

  def search
    @caff_files = []
    query = params[:query]
    if query == ""
      query = "caff"
    end
    token = session[:token]
    resp, header = @@api_user.search query, {:header_params => {"Authorization" => token}}
    session[:token] = header[:Authorization]
    if !resp.nil?
      @caff_files = resp.results
    end
  end

  def download
    token = session[:token]
    data, header = @@api_user.download params[:caff_uuid], {:header_params => {"Authorization" => token}}
    session[:token] = header[:Authorization]
    if !data.nil?
      caff_string = data.file_content_as_string
      caff = Base64.decode64 caff_string

      local_filename = "download" + session[:user_uuid] + ".caff"
      local_path = Rails.root.join('tmp', local_filename)

      File.open(local_path, 'wb') do |f|
        f.write(caff)
      end
      send_data(local_path, :filename => 'download.caff', :disposition => 'attachment')

      File.delete(local_path)
    end
  end

  def show
    @caff = nil
    filename = params[:caff_filename]
    token = session[:token]
    resp, header = @@api_user.search filename, {:header_params => {"Authorization" => token}}
    session[:token] = header[:Authorization]
    if !resp.nil?
      caff_hash = resp.results.first
      @caff = SwaggerClient::SearchResult.build_from_hash caff_hash
    end
  end

  def post_comment
    req = SwaggerClient::AddCommentRequest.new comment_params.slice(:text, :user_uuid)
    token = session[:token]
    caff_uuid = comment_params[:caff_uuid]
    data, header = @@api_user.add_comment req, caff_uuid, {:header_params => {"Authorization" => token}}
    session[:token] = header[:Authorization]
    redirect_back fallback_location: home_path
  end

  private
  def verify_user_logged_in
    if session[:user_uuid].nil?
      flash[:error] = "Only logged in users can access this page!"
      redirect_back fallback_location: home_path
    end
  end

  def comment_params
    params.require(:comment).permit(:text, :user_uuid, :caff_uuid).to_h
  end
end

webshop-client/app/helpers/caff_helper.rb
module CaffHelper
  def prettify_comment_datetime datetime_str
    dt = DateTime.strptime datetime_str.partition(".").first, "%Y-%m-%dT%H:%M:%S"
    dt.strftime "%Y-%m-%d %H:%M"
  end
end

webshop-client/app/views/caff/_caff.html.erb
<div class="card">
  <div class="card-header">
    <title class="card-header-title"><%= caff.filename %></title>
    <div class="level">
      <div class="level-right">
        <div class="level-item" style="margin-right: 20px">
          <%= link_to '<span>Download</span> <span class="icon is-small"> <i class="fas fa-download"></i> </span>'.html_safe, download_caff_path(:caff_uuid => caff.uuid),
              :method => :get, class: "button is-info"%>
        </div>
      </div>
    </div>
  </div>

  <div class="card-image is-flex is-align-content-center">
    <img src="data:image/jpeg;base64,<%= caff.preview %>" alt="" style="margin: auto">
  </div>

  <div class="card-content">
    <% caff.comments.each do |comment_hash| %>
      <% comment = SwaggerClient::CommentResult.build_from_hash comment_hash %>
       <%= render partial: "comment", :locals => {:comment => comment} %>
    <% end %>


    <%= render partial: "comment_form", :locals => {:caff_uuid => caff.uuid} %>
  </div>

</div>

webshop-client/app/views/caff/_comment.html.erb
<article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <img src="https://bulma.io/images/placeholders/128x128.png">
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= comment.user_name %></strong>
        <br>
        <%= comment.text %>
        <br>
        <small><%= prettify_comment_datetime comment.date %></small>
      </p>
    </div>
  </div>
</article>

webshop-client/app/views/caff/_comment_form.html.erb
<article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <img src="https://bulma.io/images/placeholders/128x128.png">
    </p>
  </figure>
  <div class="media-content">
    <%= form_for :comment, url: post_comment_path, method: :post do |form| %>
      <%= form.hidden_field :user_uuid, value: session[:user_uuid] %>
      <%= form.hidden_field :caff_uuid, value: caff_uuid %>
      <div class="field">
          <%= form.text_area :text, class: "textarea", placeholder: "Add a comment...", :maxlength => 100%>
      </div>
      <div class="field">
        <p class="control">
          <%= form.submit :Post, class: "button", id: "submitBtn"%>
        </p>
      </div>
    <% end %>
  </div>
</article>

webshop-client/app/views/caff/search.html.erb
<div class="section">
  <div class="columns is-multiline">
    <% @caff_files.each do |caff_hash| %>
      <% caff_file = SwaggerClient::SearchResult.build_from_hash caff_hash %>
      <div class="column is-one-quarter">
        <div class="card">
          <header class="card-header">
            <p class="card-header-title">
              <%= caff_file.filename %>
            </p>
          </header>
          <div class="card-image">
            <img src="data:image/jpeg;base64,<%= caff_file.preview %>">
          </div>
          <div class="card-footer">
            <%= link_to "Show", show_caff_path(:caff_filename => caff_file.filename), :method => :get, class: "card-footer-item" %>
            <%= link_to "Download", download_caff_path(:caff_uuid => caff_file.uuid), :method => :get, class: "card-footer-item" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

webshop-client/app/views/caff/show.html.erb
<div class="section">
  <div class="tile is-ancestor">
    <div class="tile is-parent">
      <div class="tile is-child is-2"></div>
      <div class="tile is-child is-8">
        <%= render partial: "caff", :locals => {:caff => @caff}%>
      </div>
      <div class="tile is-child is-2"></div>
    </div>
  </div>
</div>