webshop-client/config/routes.rb
Rails.application.routes.draw do
  root to: 'application#home', as: 'home'

  # User paths
  get 'register' => 'users#new'
  post 'create' => 'users#create', as: 'create_user'
  get 'upload_page' => 'users#upload_page', as: 'upload_page'
  post 'upload' => 'users#upload', as: 'upload'
  get 'admin_page' => 'users#admin_page', as: 'admin_page'
  delete 'delete' => 'users#destroy', as: 'delete_user'
  get 'edit_user' => 'users#edit_user', as: 'edit_user'
  post 'update_user' => 'users#update', as: 'update_user'


  # Caff paths
  get 'search' => 'caff#search', as: 'search'
  get 'download' => 'caff#download', as: 'download_caff'
  get 'show' => 'caff#show', as: 'show_caff'
  post 'post_comment' => 'caff#post_comment', as: 'post_comment'

  # Session paths
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'pages/home'
  get 'pages/log_in'
  get 'pages/register'
  get 'pages/show'
  get 'pages/upload'
  get 'pages/my_profile'
  get 'pages/admin_page'
  get 'pages/edit_profile'
end

webshop-client/app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <article id="notice" class="message <%= bulma_class_for type %>">
    <div class="message-header">
      <p><%= message %></p>
    </div>
  </article>
<% end %>

webshop-client/app/views/shared/_header.html.erb
<nav class="navbar is-primary" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <div class="navbar-item">
      <div class="content is-vcentered">
        <h1 class="title">
          Pangolin
        </h1>
      </div>
    </div>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">

    <% if logged_in? %>
    <div class="navbar-start">

      <div class="navbar-item">
        <%= form_tag('search', method: :get) do %>
          <div class="level">
            <div class="level-item">
              <div class="field">
                <%= text_field_tag 'query', "", class: "input", :maxlength => 20%>
              </div>

            </div>

            <div class="level-item">
              <div class="actions">
                <%= submit_tag :Search, class: "button", id: "submitBtn"%>
              </div>
            </div>

          </div>
        <% end %>
      </div>

    </div>
    <% end %>

    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if logged_in? %>
            <%=link_to "Upload", upload_page_path, method: :get, class:"button is-light" %>
            <%=link_to "Log out", logout_path, method: :get, class:"button is-light" %>
          <% else %>
            <%=link_to "Sign Up", register_path, method: :get, class:"button is-primary" %>
            <%=link_to "Log In", login_path, method: :get, class:"button is-light" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

webshop-client/app/views/shared/_menu.html.erb
<div class="section">
  <article class="panel is-primary">
    <p class="panel-heading">
      Menu
    </p>
    <a class="panel-block  <%= selected_menu_item == "Upload" ? "is-active" : "" %> " href="upload_page">
          <span class="panel-icon">
            <i class="fas fa-upload"></i>
          </span>
      Upload
    </a>
    <% if admin_user %>
      <a class="panel-block <%= selected_menu_item == "Admin Page" ? "is-active" : "" %> " href="admin_page">
            <span class="panel-icon">
              <i class="fas fa-users-cog"></i>
            </span>
        Admin Page
      </a>
    <% end %>
  </article>
</div>